### ISSUE TITLE
warpAffine borderValue is ignored

### ISSUE THREAD

**Issue by Aserus** [justadudewhohacks/opencv4nodejs#331]
I'm trying to get a white background when turning in empty space. Unfortunately, borderValue is ignored
Will this parameter be enabled?

`mat.warpAffineAsync(rotateMat, new cv.Size(mat.cols,mat.rows),cv.INTER_LINEAR,cv.BORDER_CONSTANT,new cv.Vec(255,255,255),(err,mat)=>{
...
		});`

or

`mat.warpAffineAsync(rotateMat, new cv.Size(mat.cols,mat.rows),cv.INTER_LINEAR,cv.BORDER_CONSTANT,255,(err,mat)=>{
...
		});`

[warpAffine in doc](https://docs.opencv.org/3.4.1/da/d54/group__imgproc__transform.html#ga0203d9ee5fcd28d40dbc4a1ea4451983)

**Comment by justadudewhohacks** [comment]
You are right the parameter is ignored at the moment, will provide a fix soon.

**Comment by justadudewhohacks** [comment]
Fixed in version 4.5.3.

**Comment by Aserus** [comment]
Thanks

**Comment by rainabba** [comment]
I'm on 4.7.2 and trying with the following, but still get black. Did I miss something?

```js
mat.warpAffineAsync( 
      cv.getRotationMatrix2D( rotatedRect.center, contourAngle ), 
      new cv.Size( mat.cols, mat.rows ), 
      cv.INTER_LINEAR,
      cv.BORDER_CONSTANT, 
      new cv.Vec(255,0,0),
      ( err, pageDeSkewed ) => {
          // The page is rotated as expected, but the empty areas are black
      }
    );
```
