### ISSUE TITLE
SOLVED macOS Installation issues.

### ISSUE THREAD

**Issue by EdoTrotta** [justadudewhohacks/opencv4nodejs#852]
ERROR: 

Error: Cannot find module '/Users/yourName/Desktop/project2/node_modules/opencv4nodejs/build/Release/opencv4nodejs'

Follow these steps and you should be able to install and work with this library. I've spent several hours trying to solve the issue and I think I've found something that works:

1. Install OpenCV:

- brew install opencv@4
- brew link --force opencv@4

2. Inside your repository:

- Install your node modules but avoid installing opencv4nodejs via npm i.
- Use a specific node version with nvm, node v14.18.1 or v14.17.0 will do.
- Run  `export CXXFLAGS="-std=c++14 -Wno-c++11-narrowing"` in the root of your project.
- Run `npm install opencv4nodejs`

This process should actually trigger the build in opencv4nodejs and now the module can be used without issues.

**Comment by babA409866** [comment]
i still cannot solve the problem with so many build error

**Comment by fendiflexin** [comment]
I have the same issue on windows

**Comment by EdoTrotta** [comment]
> I have the same issue on windows

This is supposed to fix macOS

**Comment by UrielCh** [comment]
Hi,
Great news for those people that do not want to build their OpenCV:
I published @u4/opencv4nodejs V 6.2.4 today,

This version autodetects the common setup path for Brew on Mac, Chocolatey on Windows, and Apt on Linux.

- Windows: 
> choco install opencv

- Mac: 
> brew install opencv

- debian:
> apt -y install libopencv-contrib-dev libopencv-dev

just define environment variable: OPENCV4NODEJS_DISABLE_AUTOBUILD=1

And your prebuild OpenCV will be used.

You may need to call:
`npx build-opencv rebuild`
or
`npx build-opencv --nobuild rebuild` (if you do not define OPENCV4NODEJS_DISABLE_AUTOBUILD variable)

**Comment by dids-reyes** [comment]
tried it but i'm still getting this error

after `npm install opencv4nodejs`

```
throw new Error('library dir does not exist: ' + libDir)
```

**Comment by Qwqw127** [comment]
> Hi, Great news for those people that do not want to build their OpenCV: I published @u4/opencv4nodejs V 6.2.4 today,
> 
> This version autodetects the common setup path for Brew on Mac, Chocolatey on Windows, and Apt on Linux.
> 
> * Windows:
> 
> > choco install opencv
> 
> * Mac:
> 
> > brew install opencv
> 
> * debian:
> 
> > apt -y install libopencv-contrib-dev libopencv-dev
> 
> just define environment variable: OPENCV4NODEJS_DISABLE_AUTOBUILD=1
> 
> And your prebuild OpenCV will be used.
> 
> You may need to call: `npx build-opencv rebuild` or `npx build-opencv --nobuild rebuild` (if you do not define OPENCV4NODEJS_DISABLE_AUTOBUILD variable)

![image](https://github.com/user-attachments/assets/9445d408-c208-490b-853d-238dd80ee241)

**Comment by 2100031988** [comment]
Hello guys, I am still getting this same issue and I have searched in many sites but not able to solve the problem
It is showing that opencv4nodejs is not there in node_modules inside the release folder.

**Comment by costinchivu** [comment]
rename it, this is far from being SOLVED. same error as above
